import type { HeroRule } from "./rules.ts";
import { buildLexicalMask, sourceForScope, type LexicalMask } from "./lexicalMask.ts";

// ---------------------------------------------------------------------------
// Shared deterministic pattern matcher. This is the SINGLE source of truth
// for what "a rule matches a line" means — used by both the production
// scanner (hero-scanner) and the offline rule-evolution engine (hero-ruleforge).
//
// Why this matters: hero-ruleforge scores candidate rules against a golden
// corpus to decide whether to promote them. If ruleforge used different
// matching semantics than the scanner, a rule could look great in evaluation
// and behave differently in production. Sharing this module makes that
// impossible by construction.
// ---------------------------------------------------------------------------

export interface PatternMatch {
  line: number; // 1-indexed
  column: number; // 1-indexed
  endColumn: number;
  snippet: string;
}

/**
 * Compile a rule pattern into a JS RegExp. Rules may use a leading inline flag
 * group like `(?i)` (PCRE-style, portable with a future native engine); we
 * translate it into real JS flags since bare `(?i)` is not valid in JS regex.
 */
export function compilePattern(source: string, flags: string = ""): RegExp {
  let body = source;
  const inline = /^\(\?([a-z]+)\)/.exec(body);
  const collected = new Set(flags.split(""));
  if (inline?.[1]) {
    for (const f of inline[1]) if ("gimsuy".includes(f)) collected.add(f);
    body = body.slice(inline[0].length);
  }
  return new RegExp(body, [...collected].join(""));
}

/**
 * Heuristic static check for classic ReDoS shapes (nested/overlapping
 * quantifiers) in an UNTRUSTED regex source — e.g. dress-code patterns
 * authored by an org member or generated by an LLM, which then run
 * unsandboxed against arbitrary source text with no execution timeout (a
 * single `RegExp.exec` can't be preempted mid-run in Node). Not exhaustive,
 * but catches the shapes that actually cause catastrophic backtracking:
 * `(x+)+`, `(x*)*`, `(x+)*`, `(x{2,})+`, and severely long patterns that are
 * hard to reason about at all. Only applied to overlay (dress-code) rules —
 * the canonical RULES catalog is authored/reviewed by the CodeHero team.
 */
export function isUnsafeRegex(source: string): boolean {
  if (source.length > 300) return true;
  // A quantified group whose own body contains another quantifier — the
  // textbook nested-quantifier ReDoS shape. Body is restricted to "no nested
  // parens" so this check itself stays a fast, linear regex.
  if (/\([^()]*[+*][^()]*\)[+*]/.test(source)) return true;
  if (/\([^()]*\{\d+,\d*\}[^()]*\)[+*]/.test(source)) return true;
  return false;
}

export interface MatchOptions {
  /**
   * Máscara já calculada. O scanner monta UMA por arquivo e reusa nas 493
   * regras; calcular por regra seria 493 varreduras do mesmo texto.
   */
  mask?: LexicalMask;
  /** Perfil léxico quando a máscara não vem pronta (ver lexicalProfileFor). */
  profile?: string;
}

/**
 * Apply a rule's pattern (regex + optional `unless` guard) to source text.
 *
 * A regex casa sobre o texto MASCARADO conforme `pattern.scope`, mas o snippet
 * vem da linha ORIGINAL: quem lê o relatório precisa ver o código como ele é,
 * não com os comentários apagados.
 */
export function matchPattern(
  pattern: HeroRule["pattern"],
  source: string,
  opts: MatchOptions = {},
): PatternMatch[] {
  const re = compilePattern(pattern.regex, pattern.flags ?? "");
  const unless = pattern.unless ? compilePattern(pattern.unless, "") : null;

  // Construir aqui quando não vier pronta mantém scanner e ruleforge com a
  // MESMA semântica — que é a razão de este módulo existir.
  const mask = opts.mask ?? buildLexicalMask(source, opts.profile ?? "clike");
  const alvo = sourceForScope(pattern.scope, source, mask);

  const linhasAlvo = alvo.split(/\r?\n/);
  const linhasCruas = source.split(/\r?\n/);
  const matches: PatternMatch[] = [];

  for (let i = 0; i < linhasAlvo.length; i++) {
    const linha = linhasAlvo[i] ?? "";
    const m = re.exec(linha);
    if (!m) continue;
    const crua = linhasCruas[i] ?? linha;
    // `unless` avalia a linha CRUA, não a mascarada.
    //
    // A versão anterior usava a mascarada, com o argumento de que um
    // "eslint-disable" dentro de uma string não deveria desligar a regra. O
    // raciocínio estava invertido: marcador de supressão vive em COMENTÁRIO —
    // `# nosec`, `// sanitize: ...`, `// eslint-disable` — e o comentário é
    // exatamente o que a máscara apaga.
    //
    // Efeito medido: NENHUMA regra com `unless` baseado em comentário podia ser
    // suprimida. Uma justificativa escrita ao lado do código não tinha efeito
    // nenhum, o que torna o gate impossível de calibrar honestamente.
    if (unless && unless.test(crua)) continue;
    const col = (m.index ?? 0) + 1;
    matches.push({ line: i + 1, column: col, endColumn: col + m[0].length, snippet: crua.trim() });
  }
  return matches;
}
