import type { HeroRule } from "./rules.ts";

// ---------------------------------------------------------------------------
// Shared deterministic pattern matcher. This is the SINGLE source of truth
// for what "a rule matches a line" means — used by both the production
// scanner (hero-scanner) and the offline rule-evolution engine (hero-ruleforge).
//
// Why this matters: hero-ruleforge scores candidate rules against a golden
// corpus to decide whether to promote them. If ruleforge used different
// matching semantics than the scanner, a rule could look great in evaluation
// and behave differently in production. Sharing this module makes that
// impossible by construction.
// ---------------------------------------------------------------------------

export interface PatternMatch {
  line: number; // 1-indexed
  column: number; // 1-indexed
  endColumn: number;
  snippet: string;
}

/**
 * Compile a rule pattern into a JS RegExp. Rules may use a leading inline flag
 * group like `(?i)` (PCRE-style, portable with a future native engine); we
 * translate it into real JS flags since bare `(?i)` is not valid in JS regex.
 */
export function compilePattern(source: string, flags: string = ""): RegExp {
  let body = source;
  const inline = /^\(\?([a-z]+)\)/.exec(body);
  const collected = new Set(flags.split(""));
  if (inline?.[1]) {
    for (const f of inline[1]) if ("gimsuy".includes(f)) collected.add(f);
    body = body.slice(inline[0].length);
  }
  return new RegExp(body, [...collected].join(""));
}

/**
 * Heuristic static check for classic ReDoS shapes (nested/overlapping
 * quantifiers) in an UNTRUSTED regex source — e.g. dress-code patterns
 * authored by an org member or generated by an LLM, which then run
 * unsandboxed against arbitrary source text with no execution timeout (a
 * single `RegExp.exec` can't be preempted mid-run in Node). Not exhaustive,
 * but catches the shapes that actually cause catastrophic backtracking:
 * `(x+)+`, `(x*)*`, `(x+)*`, `(x{2,})+`, and severely long patterns that are
 * hard to reason about at all. Only applied to overlay (dress-code) rules —
 * the canonical RULES catalog is authored/reviewed by the CodeHero team.
 */
export function isUnsafeRegex(source: string): boolean {
  if (source.length > 300) return true;
  // A quantified group whose own body contains another quantifier — the
  // textbook nested-quantifier ReDoS shape. Body is restricted to "no nested
  // parens" so this check itself stays a fast, linear regex.
  if (/\([^()]*[+*][^()]*\)[+*]/.test(source)) return true;
  if (/\([^()]*\{\d+,\d*\}[^()]*\)[+*]/.test(source)) return true;
  return false;
}

/** Apply a rule's pattern (regex + optional `unless` guard) to source text. */
export function matchPattern(pattern: HeroRule["pattern"], source: string): PatternMatch[] {
  const re = compilePattern(pattern.regex, pattern.flags ?? "");
  const unless = pattern.unless ? compilePattern(pattern.unless, "") : null;
  const lines = source.split(/\r?\n/);
  const matches: PatternMatch[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? "";
    const m = re.exec(line);
    if (!m) continue;
    if (unless && unless.test(line)) continue;
    const col = (m.index ?? 0) + 1;
    matches.push({ line: i + 1, column: col, endColumn: col + m[0].length, snippet: line.trim() });
  }
  return matches;
}
