--#SET TERMINATOR @

-- Procedure de consulta de saldo. Compila e roda.
-- O defeito: P_CONTA vem do chamador e e concatenado direto no SQL
-- executado por EXECUTE IMMEDIATE. Injecao classica, em DB2.
CREATE PROCEDURE CONSULTA_SALDO
  (IN P_CONTA VARCHAR(20), IN P_ORDEM VARCHAR(50), OUT P_SALDO DECIMAL(11,2))
  LANGUAGE SQL
BEGIN
  DECLARE V_SQL VARCHAR(1000);
  DECLARE V_LIDOS INT DEFAULT 0;
  DECLARE C_MOVTO CURSOR FOR SELECT VALOR FROM MOVIMENTO;
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET P_SALDO = 0;

  SET V_SQL = 'SELECT SALDO FROM CONTAS WHERE ID = ''' || P_CONTA ||
              ''' ORDER BY ' || P_ORDEM;

  PREPARE S1 FROM V_SQL;

  WHILE V_LIDOS < 100 DO
    IF V_LIDOS = 50 THEN
      EXECUTE IMMEDIATE V_SQL;
    END IF;
    SET V_LIDOS = V_LIDOS + 1;
  END WHILE;

  CALL AUDITORIA.REGISTRA(P_CONTA);
END@
