name: CodeHero Analysis
on:
  pull_request:
  push:
    branches: [main]

jobs:
  codehero:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: nbsjunior/codehero/packages/github-action@main
        with:
          server-url: ${{ vars.HERO_CORE_URL }}
          token: ${{ secrets.HERO_TOKEN }}
          org-id: "o3wzXUVdMjpzBG3eAYB6"
          project-id: "bEkjSpjt5FFXMwN194Ts"
          repo-id: "PtOaXq5dcZQhFE6HPtI4"
          path: "."
          fail-on: CRITICAL
